### PR TITLE
Add travis config to pull build dependencies

### PR DESCRIPTION
**Pull request by tstrass**
This is just copied over from https://github.com/projecttacoma/draft-measures/pull/1. Just to be sure, I tested it with a fhir-patient-generator `make` command and the [build](https://travis-ci.com/github/projecttacoma/connectathon/builds/154242383) passed.

### CODE REVIEW

**Review by hossenlopp — APPROVED** [review]
This looks good. My only wonder is if we should do something to ensure `fhir-bundle-calculator` is available as a command to be run and is the correct version.

**Comment by okeefm** [comment]
@hossenlopp I believe that should be covered by James's task in the current sprint.

**Comment by hossenlopp** [comment]
@okeefm Yeah, it will! :)

**Review by okeefm — APPROVED** [review]
Looks good to me. works in travis, and the setup script works on my machine.

**Pull request merged**
